### ISSUE TITLE
Filter plugin to only show tags used in current category

### ISSUE THREAD

**Issue by rschumachr** [zeroseven/pagebased_blog#2]
Hi there,

We're using pagebased_blog on a project where we use it for different types of entries, once for a blog and once for a list of references. On both types we're using tags. While on the reference entries the tags are purely descriptional, on the blog entries we're also using the tags to filter through the blog posts (the filter plugin is inserted on the blog-category page just above the list plugin).

The filtering works without any issue but we noticed that it shows us all the tags on the whole project, so not just the tags that are used on the blog posts but also the ones that are only used on reference entries. That means when we filter one of those reference-tags it shows us no results, since the list plugin only shows blog-entries.

Is there a way to only show tags that are in use on the current category-page?

We have copied the template for the filter plugin in order to add some custom html and to remove all filters except for the tag filter. Is there perhaps a way to add a parameter to the "pagebased:filter.link" viewhelper to filter out any unused tags?

Thank you

**Comment by rschumachr** [comment]
Update: We decided to use topics for our blog post filtering and keep the tags for the reference entries. That way we only see the topics in the filter plugin and could solve our issue this way.

**Comment by raphaelthanner** [comment]
Hi @rschumachr,

I just tested this with the latest version of the pageabsed extension in dev-master. In my environment, only the tags of the plugin's objects are displayed.

We will release a new version soon.

Continue to have fun with the extension
